"""Package admin workflow and booking history

Revision ID: 9689b7dd6a0b
Revises: c0ca92141d57
Create Date: 2025-09-20 23:40:23.530393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9689b7dd6a0b'
down_revision = 'c0ca92141d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('status_updated_at')
        batch_op.drop_column('admin_note')

    op.drop_table('booking_status_history')
    # ### end Alembic commands ###
