"""Consultation workflow

Revision ID: 9907d9c0e126
Revises: d8d3d4487d8a
Create Date: 2025-09-18 21:36:40.118451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9907d9c0e126'
down_revision = 'd8d3d4487d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Cleanup in case a previous failed attempt left artifacts (SQLite is non-transactional for DDL)
    op.execute(sa.text("DROP TABLE IF EXISTS consultation_response"))

    op.create_table('consultation_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultation.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Ensure existing rows have a question value before enforcing NOT NULL
    op.execute(sa.text("""
        UPDATE consultation
        SET question = 'استشارة بدون عنوان'
        WHERE question IS NULL OR TRIM(question) = ''
    """))

    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('answered_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('question',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('answered_at')
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('updated_at')

    op.drop_table('consultation_response')
    # ### end Alembic commands ###
