"""Add booking service selection

Revision ID: c0ca92141d57
Revises: f04402cb54d4
Create Date: 2025-09-20 23:23:26.674144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ca92141d57'
down_revision = 'f04402cb54d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_service_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('package_service_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('service_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['package_service_id'], ['package_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_service_selection')
    # ### end Alembic commands ###
