"""modify the consultation

Revision ID: d8d3d4487d8a
Revises: 52a618ec2c87
Create Date: 2025-09-17 13:33:35.849255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d3d4487d8a'
down_revision = '52a618ec2c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ### 
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question_for', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.Text(), nullable=True))
        # الحل: نضيف server_default='' عشان البيانات القديمة تمر
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('contact_method', sa.String(length=20), nullable=False, server_default=''))
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('consultation_type')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('consultation_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('contact_method')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('medical_history')
        batch_op.drop_column('age')
        batch_op.drop_column('gender')
        batch_op.drop_column('question_for')
        batch_op.drop_column('description')
        batch_op.drop_column('question')
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
