"""Add doctor credentials

Revision ID: f04402cb54d4
Revises: 9907d9c0e126
Create Date: 2025-09-18 21:48:00.028111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04402cb54d4'
down_revision = '9907d9c0e126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_doctor_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint('uq_doctor_email', type_='unique')
        batch_op.drop_column('last_login')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
